### ISSUE TITLE
LNK Go neveiki

### ISSUE THREAD

**Issue by fogers777** [Vytax/kodi-repo#1]
Neveikia LNK Go addon'as. Butu smagu, jei pataisytumet.

**Comment by Vytax** [comment]
Dėkui. Padariau greitą pataisymą. Turėtų veikti. Jeigu ne, reikės taisyti rimčiau.

**Comment by fogers777** [comment]
Dekui uz operatyvuma! teks matyt rimciau taisyt :) negroja..

23:12:43 298432.875000 T:1957106608  NOTICE: DVDPlayer: Opening: rtmp://stream.lnk.lt/vod/ playpath=mp4:/new/vod/aktualai-pratesimas/20160810-Litofcai-Taromatas-MPEG-2-Program-stream-15-Mbps.mp4
23:12:43 298432.875000 T:1957106608 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
23:12:43 298432.875000 T:1508975600  NOTICE: Creating InputStream
23:12:43 298432.937500 T:1508975600   ERROR: rtmp server sent error
23:12:43 298432.937500 T:1508975600   ERROR: rtmp server requested close
23:12:43 298432.937500 T:1508975600   ERROR: CDVDPlayer::OpenInputStream - error opening [rtmp://stream.lnk.lt/vod/ playpath=mp4:/new/vod/aktualai-pratesimas/20160810-Litofcai-Taromatas-MPEG-2-Program-stream-15-Mbps.mp4]
23:12:43 298432.937500 T:1508975600  NOTICE: CDVDPlayer::OnExit()
23:12:43 298432.937500 T:1957106608   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.lnk.lt/?url=%2Fvisi-video%2Faktualai-pratesimas%2Fziurek-litofcai-taromatas&mode=10]
23:12:43 298432.937500 T:1957106608  NOTICE: CDVDPlayer::CloseFile()
23:12:43 298432.937500 T:1957106608  NOTICE: DVDPlayer: waiting for threads to exit
23:12:43 298432.937500 T:1957106608  NOTICE: DVDPlayer: finished waiting
23:12:43 298432.937500 T:1957106608  NOTICE: CDVDPlayer::CloseFile()
23:12:43 298432.937500 T:1957106608  NOTICE: DVDPlayer: waiting for threads to exit
23:12:43 298432.937500 T:1957106608  NOTICE: DVDPlayer: finished waiting

**Comment by Vytax** [comment]
Pas jus vis dar sena įskiepio versija. Atsinaujinkite. :)

**Comment by fogers777** [comment]
Va, su 0.3 vaziuoja dabar:) aciu labai! Puikus iskiepiai, dekui uz puiku darba.
