### ISSUE TITLE
LNK GO plugin does not work on dietpi 6.9

### ISSUE THREAD

**Issue by ModestasB** [Vytax/kodi-repo#3]
Could you please review it and may be release update for this

Kodi logs:

> login as: root
> root@192.168.5.2's password:
> 
> The programs included with the Debian GNU/Linux system are free software;
> the exact distribution terms for each program are described in the
> individual files in /usr/share/doc/*/copyright.
> 
> Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
> permitted by applicable law.
>  āāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāā
>  DietPi     | 09:26 | Mon 02/07/18
>  āāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāā
>  v6.9       | RPi 2 Model B (armv7l)
>  āāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāā
>  eth0       | 192.168.5.2
>  āāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāāā
>  DietPi Core Team   : Daniel Knight (founder), MichaIng, K-Plan
>  Web                : https://DietPi.com | https://twitter.com/dietpi_
>  Donate             : https://goo.gl/pzISt9
>  DietPi web hosting : Powered by https://MyVirtualServer.com
> 
>  dietpi-launcher  = All the DietPi programs in one place.
>  dietpi-config    = Feature rich configuration tool for your device.
>  dietpi-software  = Select optimized software for installation.
>  htop             = Resource monitor.
>  cpu              = Shows CPU information and stats.
> 
> root@DietPi:~# mc
> /root/.kodi/temp/kodi.log                                                                                                         27356/36203              75%
> 11:25:14.547 T:1911525376 WARNING: Previous line repeats 1 times.
> 11:25:14.547 T:1911525376   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
> 11:25:15.127 T:1462760192 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
> 11:25:18.564 T:1659691776 WARNING: Previous line repeats 2 times.
> 11:25:18.565 T:1659691776   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.IOError'>
>                                             Error Contents: ('http protocol error', 0, 'got a bad status line', None)
>                                             Traceback (most recent call last):
>                                               File "/root/.kodi/addons/plugin.video.lnk.lt/default.py", line 170, in <module>
>                                                 loadCategory(mode, page, url)
>                                               File "/root/.kodi/addons/plugin.video.lnk.lt/default.py", line 59, in loadCategory
>                                                 videos = lnk.get_latest_videos(page)
>                                               File "/root/.kodi/addons/plugin.video.lnk.lt/liblnk.py", line 55, in get_latest_videos
>                                                 return getInfo(LNK_LATEST_VIDEOS % (page * 35))
>                                               File "/root/.kodi/addons/plugin.video.lnk.lt/liblnk.py", line 59, in getInfo
>                                                 html = getURL(url)
>                                               File "/root/.kodi/addons/plugin.video.lnk.lt/liblnk.py", line 21, in getURL
>                                                 res = urllib.urlopen(url)
>                                               File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
>                                                 return opener.open(url)
>                                               File "/usr/lib/python2.7/urllib.py", line 213, in open
>                                                 return getattr(self, name)(url)
>                                               File "/usr/lib/python2.7/urllib.py", line 357, in open_http
>                                                 'got a bad status line', None)
>                                             IOError: ('http protocol error', 0, 'got a bad status line', None)
>                                             -->End of Python script error report<--
> 11:25:18.706 T:1911525376   ERROR: GetDirectory - Error getting plugin://plugin.video.lnk.lt/?mode=1&page=0
> 11:25:18.712 T:1911525376   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.lnk.lt/?mode=1&page=0) failed
> 11:25:18.858 T:1462760192 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
> 11:25:21.834 T:1684857600 WARNING: Previous line repeats 5 times.
> 11:25:21.834 T:1684857600   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.IOError'>
>                                             Error Contents: ('http protocol error', 0, 'got a bad status line', None)
>                                             Traceback (most recent call last):
>                                               File "/root/.kodi/addons/plugin.video.lnk.lt/default.py", line 170, in <module>
>                                                 loadCategory(mode, page, url)
>                                               File "/root/.kodi/addons/plugin.video.lnk.lt/default.py", line 61, in loadCategory
>                                                 videos = lnk.get_popular_videos(page)
>                                               File "/root/.kodi/addons/plugin.video.lnk.lt/liblnk.py", line 52, in get_popular_videos
>                                                 return getInfo(LNK_POPULAR_VIDEOS % (page * 35))
>                                               File "/root/.kodi/addons/plugin.video.lnk.lt/liblnk.py", line 59, in getInfo
>  1Help          2UnWrap         3Quit           4Hex            5Goto           6              7Search         8Raw            9Format        10Quit
>

**Comment by Vytax** [comment]
Fixed in the last commit.
